src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $Name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }
}

src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Tests\Fixtures\EntityInterfaceA;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event implements EntityInterfaceA
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Location;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Event;
use App\Form\EventFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventController extends AbstractController
{
    /**
     * @Route("/event", name="event")
     */
    public function createEvent(Request $request)
    {
        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();
        $event = new Event();
        $form = $this->createForm(EventFormType::class, $event);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid())
        {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();
            $category = $this->getDoctrine()->getRepository(Category::class)->findOneBy(['Name' => $event->getCategory()]);

            // do anything else you need here, like send an email
            return $this->redirectToRoute('subsmailer', ['slug' => $category->getId()]);
        }

        return $this->render('event/create.html.twig', [
            'eventForm' => $form->createView(),
            'categories' => $categories
        ]);
    }

    /**
     * @Route("/event/edit/{id}", name="event_edit")
     */
    public function editEvent(Request $request, $id)
    {
        $event = new Event();
        $event = $this->getDoctrine()->getRepository(Event::class)->find($id);
        $form = $this->createForm(EventFormType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            // do anything else you need here, like send an email

            return $this->redirectToRoute('home_page');
        }
        return $this->render('event/edit.html.twig', [
            'eventForm' => $form->createView(),
        ]);
    }
    /**
     * @Route("/event/{id}", name="view_event")
     */
    public function viewEvent($id)
    {
        $events = $this->getDoctrine()
            ->getRepository(Event::class)
            ->find($id);

        return $this->render('event/view.html.twig', [
            'events'=>$events
        ]);
    }

    /**
     * @Route("/event/delete/{id}", name="delete_event")
     */
    public function Delete($id)
    {
        $events = $this->getDoctrine()->getRepository(Event::class)->find($id);
        $entitymanager = $this->getDoctrine()->getManager();
        $entitymanager->remove($events);
        $entitymanager->flush();
        return $this->redirectToRoute('home_page');
    }
}

templates/event/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create event{% endblock %}

{% block dashboard %}
    <h1>Register</h1>

    {{ form_start(eventForm) }}
        {{ form_row(eventForm.Title) }}
        {{ form_row(eventForm.Description) }}
        {{ form_row(eventForm.Category) }}
        {{ form_row(eventForm.Date) }}
        {{ form_row(eventForm.Location) }}
        {{ form_row(eventForm.Price) }}
        <button class="submit">Create</button>

    {{ form_end(eventForm) }}

    Categories:
{% for category in categories %}
    <p>{{ category.name }}</p>
    {% endfor %}
{% endblock %}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit event{% endblock %}

{% block dashboard %}
    <h1>Edit event</h1>

    {{ form_start(eventForm) }}
    {{ form_row(eventForm.Title) }}
    {{ form_row(eventForm.Description) }}
    {{ form_row(eventForm.Category) }}
    {{ form_row(eventForm.Date) }}
    {{ form_row(eventForm.Location) }}
    {{ form_row(eventForm.Price) }}
    <button class="submit">Edit</button>
    {{ form_end(eventForm) }}
{% endblock %}

templates/event/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}View Event{% endblock %}

{% block dashboard %}

    <h1>{{ events.title }}</h1>
    <p>Category: {{ events.category }}</p>
    <p style="word-wrap: break-spaces">{{ events.description }}</p>
    <p>Location: {{ events.location }}</p>
    <p>Date: {{ events.date.format("Y-m-d") }}</p>
    <p>Price: {{ events.price }} Euros</p>
    {% if (app.token.username=='admin') %}
    <a href="{{ path('delete_event', {id: events.id}) }}">Delete</a>
        <a href="{{ path('event_edit', {id: events.id}) }}">Edit</a>
    {% endif %}
{% endblock %}